sudo: false
language: ruby

rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.2.9

before_install:
  - | # epic build time improvement - see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

install:
  - bundle install
  - bundle install --gemfile=test/acceptance/rails4.2/Gemfile
  - bundle install --gemfile=test/acceptance/rails5.0/Gemfile
  - npm install -g elm
  - | # epic build time improvement, continued:
    mv $(npm config get prefix)/bin/elm-make $(npm config get prefix)/bin/elm-make-old
    printf "#\041/bin/bash\n\necho \"Running elm-make with sysconfcpus -n 2\"\n\n$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make-old \"\$@\"" > $(npm config get prefix)/bin/elm-make
    chmod +x $(npm config get prefix)/bin/elm-make

cache:
  bundler: true
  directories:
    - node_modules
    - sysconfcpus

